name: rust

services:
  rust-server:
    image: "pfeiffermax/rust-game-server:latest"
    pull_policy: always
    # Container name will be managed by Coolify
    cpus: 4
    mem_limit: 8gb
    command:
      - "+server.ip"
      - "0.0.0.0"
      - "+server.port"
      - "28015"
      - "+server.hostname"
      - ${SERVER_NAME}
      - "+server.maxplayers"
      - "10"
      - "+server.worldsize"
      - "1000"
      - "+server.gamemode"
      - "vanilla"
      - "+server.seed"
      - "666"
      - "+server.identity"
      - ${SERVER_NAME}
      - "+rcon.ip"
      - "0.0.0.0"
      - "+rcon.port"
      - "28016"
      - "+rcon.password"
      - ${RCON_PASSWORD:-${SERVICE_PASSWORD_RUSTSERVER}}
      - "+rcon.web"
      - "1"
      - "-logfile"
      - "/var/log/rust-server-${SERVER_NAME}.log"
    ports:
      - "28015:28015/udp"
      - "28016:28016/tcp"
    volumes:
      - type: volume
        source: server_identity
        target: "/srv/rust/server/${SERVER_NAME}"
      - type: bind
        source: ./logs
        target: /var/log
        is_directory: true
    environment:
      - SERVER_NAME=${SERVER_NAME:-RustServer}
      - RCON_PASSWORD=${RCON_PASSWORD:-${SERVICE_PASSWORD_RUSTSERVER}}
      # We'll use RCON web interface with Traefik
      - SERVICE_FQDN_RUSTRCON=/
      - SERVICE_FQDN_RUSTRCON_28016
    labels:
      - traefik.enable=true
      # Only RCON web interface can be proxied (when enabled)
      - "traefik.http.routers.rust-rcon.rule=Host(`${SERVICE_FQDN_RUSTRCON}`)"
      - "traefik.http.routers.rust-rcon.entrypoints=http"
      - "traefik.http.services.rust-rcon.loadbalancer.server.port=28016"
      # Direct game port exposure is handled by the ports section
      # Do not proxy UDP game traffic through Traefik

  rcon-cli:
    image: "outdead/rcon:latest"
    depends_on:
      - rust-server
    command:
      - "./rcon"
      - "--address"
      - "rust-server:28016"
      - "--password"
      - ${RCON_PASSWORD:-${SERVICE_PASSWORD_RUSTSERVER}}
    environment:
      - RCON_PASSWORD=${RCON_PASSWORD:-${SERVICE_PASSWORD_RUSTSERVER}}

volumes:
  server_identity:
    name: "rust-server-identity-${SERVER_NAME}" 