name: rust

services:
  rust-server:
    image: "pfeiffermax/rust-game-server:latest"
    pull_policy: always
    # Container name will be managed by Coolify
    cpus: 4
    mem_limit: 8gb
    command:
      - "+server.ip"
      - "0.0.0.0"
      - "+server.port"
      - "28015"
      - "+server.hostname"
      - "RustServer"
      - "+server.maxplayers"
      - "10"
      - "+server.worldsize"
      - "1000"
      - "+server.gamemode"
      - "vanilla"
      - "+server.seed"
      - "666"
      - "+server.identity"
      - "RustServer"
      - "+rcon.ip"
      - "0.0.0.0"
      - "+rcon.port"
      - "28016"
      - "+rcon.password"
      - "rustpassword"
      - "+rcon.web"
      - "1"
      - "-logfile"
      - "/var/log/rust-server.log"
    ports:
      - "28015:28015/udp"
      - "28016:28016/tcp"
    volumes:
      - type: volume
        source: server_identity
        target: "/srv/rust/server/RustServer"
      - type: bind
        source: ./logs
        target: /var/log
        is_directory: true
    environment:
      - SERVER_NAME=RustServer
      - RCON_PASSWORD=rustpassword
      # Coolify's predefined variables
      - COOLIFY_FQDN=${COOLIFY_FQDN}
      - COOLIFY_URL=${COOLIFY_URL}
      - COOLIFY_RESOURCE_UUID=${COOLIFY_RESOURCE_UUID}
    labels:
      - traefik.enable=true
      # Only RCON web interface can be proxied (when enabled)
      - "traefik.http.routers.rust-rcon.rule=Host(`${COOLIFY_FQDN}`)"
      - "traefik.http.routers.rust-rcon.entrypoints=http"
      - "traefik.http.services.rust-rcon.loadbalancer.server.port=28016"
      # Direct game port exposure is handled by the ports section
      # Do not proxy UDP game traffic through Traefik

  rcon-cli:
    image: "outdead/rcon:latest"
    depends_on:
      - rust-server
    command:
      - "./rcon"
      - "--address"
      - "rust-server:28016"
      - "--password"
      - "rustpassword"
    environment:
      - RCON_PASSWORD=rustpassword

volumes:
  server_identity:
    name: "rust-server-identity" 