name: rust

services:
  rust-server:
    image: "pfeiffermax/rust-game-server:latest"
    pull_policy: always
    container_name: "rust-server"
    cpus: 4
    mem_limit: 8gb
    command:
      - "+server.ip"
      - "0.0.0.0"
      - "+server.port"
      - "28015"
      - "+server.hostname"
      - "Rust Server"
      - "+server.maxplayers"
      - "10"
      - "+server.worldsize"
      - "1000"
      - "+server.gamemode"
      - "vanilla"
      - "+server.seed"
      - "666"
      - "+server.identity"
      - "Rust Server"
      - "+rcon.ip"
      - "0.0.0.0"
      - "+rcon.port"
      - "28016"
      - "+rcon.password"
      - "password"
      - "+rcon.web"
      - "0"
      - "-logfile"
      - "/var/log/rust-server.log"
    ports:
      - "28015:28015/udp"
      - "28016:28016/tcp"
    environment:
      - "SERVER_NAME=Rust Server"
      - "RCON_PASSWORD=password"
      - "SERVICE_FQDN_RUSTSERVER"
    volumes:
      - type: volume
        source: server_identity
        target: "/srv/rust/server/Rust Server"
      - type: bind
        source: /var/log/docker-compose/rust
        target: /var/log
        is_directory: true

  rcon-cli:
    image: "outdead/rcon:latest"
    container_name: "rcon-cli"
    depends_on:
      - rust-server
    command:
      - "./rcon"
      - "--address"
      - "rust-server:28016"
      - "--password"
      - "password"
    environment:
      - "RCON_PASSWORD=password"

volumes:
  server_identity:
    name: "rust-server-identity-Rust Server" 