name: rust

services:
  rust-server:
    image: "pfeiffermax/rust-game-server:latest"
    pull_policy: always
    container_name: "rust-server"
    cpus: 2
    mem_limit: 16gb
    command:
      - "+server.ip"
      - "0.0.0.0"
      - "+server.port"
      - "28015"
      - "+server.hostname"
      - ${SERVER_NAME}
      - "+server.maxplayers"
      - "10"
      - "+server.worldsize"
      - "1000"
      - "+server.gamemode"
      - "vanilla"
      - "+server.seed"
      - "666"
      - "+server.identity"
      - ${SERVER_NAME}
      - "+rcon.ip"
      - "0.0.0.0"
      - "+rcon.port"
      - "28016"
      - "+rcon.password"
      - ${RCON_PASSWORD}
      - "+rcon.web"
      - "0"
      - "-logfile"
      - "/var/log/rust-server-${SERVER_NAME}.log"
    ports:
      - "28015:28015/udp"
      - "28016:28016/tcp"
    volumes:
      - type: volume
        source: server_identity
        target: "/srv/rust/server/${SERVER_NAME}"
      - type: bind
        source: /var/log/docker-compose/rust
        target: /var/log
    env_file: .env

  rcon-cli:
    image: "outdead/rcon:latest"
    container_name: "rcon-cli"
    depends_on:
      - rust-server
    command:
      - "./rcon"
      - "--address"
      - "rust-server:28016"
      - "--password"
      - ${RCON_PASSWORD}

volumes:
  server_identity:
    name: "rust-server-identity-${SERVER_NAME}"
